import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BarChart, BookOpen, LineChart } from "lucide-react";
import PageLayout from "@/components/PageLayout";
import PageBreadcrumbs from "@/components/PageBreadcrumbs";
const EarthquakeStatistics = () => {
    return (_jsxs(PageLayout, { children: [_jsx(PageBreadcrumbs, { items: [
                    { label: "Earthquake Statistics" }
                ] }), _jsx("section", { className: "bg-techtoniq-blue-light/30 py-12", children: _jsxs("div", { className: "container", children: [_jsx("h1", { className: "mb-4 text-3xl font-bold text-techtoniq-earth-dark", children: "Earthquake Statistics" }), _jsx("p", { className: "text-techtoniq-earth", children: "Comprehensive data and trends on global earthquake activity" })] }) }), _jsx("section", { className: "py-12", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "mb-12 rounded-lg border bg-white p-6 shadow-sm", children: [_jsx("h2", { className: "mb-6 text-xl font-semibold text-techtoniq-earth-dark", children: "Global Statistics" }), _jsx("div", { className: "flex items-center justify-center", children: _jsxs("div", { className: "flex flex-col items-center", children: [_jsx(BarChart, { className: "mb-4 h-20 w-20 text-techtoniq-blue opacity-60" }), _jsx("p", { className: "text-center text-techtoniq-earth", children: "Global earthquake statistics would be displayed here" })] }) })] }), _jsxs("div", { className: "mb-12 rounded-lg border bg-white p-6 shadow-sm", children: [_jsx("h2", { className: "mb-6 text-xl font-semibold text-techtoniq-earth-dark", children: "Yearly Trends" }), _jsx("div", { className: "flex items-center justify-center", children: _jsxs("div", { className: "flex flex-col items-center", children: [_jsx(LineChart, { className: "mb-4 h-20 w-20 text-techtoniq-blue opacity-60" }), _jsx("p", { className: "text-center text-techtoniq-earth", children: "Yearly earthquake trends would be displayed here" })] }) })] }), _jsxs("div", { className: "rounded-lg border bg-white p-6 shadow-sm", children: [_jsx("h2", { className: "mb-6 text-xl font-semibold text-techtoniq-earth-dark", children: "Understanding the Data" }), _jsx("div", { className: "flex items-center justify-center", children: _jsxs("div", { className: "flex flex-col items-center", children: [_jsx(BookOpen, { className: "mb-4 h-20 w-20 text-techtoniq-blue opacity-60" }), _jsx("p", { className: "text-center text-techtoniq-earth", children: "Explanations about earthquake data would be displayed here" })] }) })] })] }) })] }));
};
export default EarthquakeStatistics;
