import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MapPin, Map } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import PageLayout from "@/components/PageLayout";
import PageBreadcrumbs from "@/components/PageBreadcrumbs";
const EarthquakeByRegion = () => {
    return (_jsxs(PageLayout, { children: [_jsx(PageBreadcrumbs, { items: [
                    { label: "Earthquake by Region" }
                ] }), _jsx("section", { className: "bg-techtoniq-blue-light/30 py-12", children: _jsxs("div", { className: "container", children: [_jsx("h1", { className: "mb-4 text-3xl font-bold text-techtoniq-earth-dark", children: "Earthquake by Region" }), _jsx("p", { className: "text-techtoniq-earth", children: "Explore seismic data by geographic area" })] }) }), _jsx("section", { className: "py-12", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "mb-8", children: [_jsx("h2", { className: "mb-4 text-xl font-semibold text-techtoniq-earth-dark", children: "Select Region" }), _jsxs(Select, { children: [_jsx(SelectTrigger, { className: "w-full max-w-xs", children: _jsx(SelectValue, { placeholder: "Select a region" }) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "north-america", children: "North America" }), _jsx(SelectItem, { value: "south-america", children: "South America" }), _jsx(SelectItem, { value: "europe", children: "Europe" }), _jsx(SelectItem, { value: "asia", children: "Asia" }), _jsx(SelectItem, { value: "australia", children: "Australia & Oceania" }), _jsx(SelectItem, { value: "africa", children: "Africa" })] })] })] }), _jsxs("div", { className: "mb-12 rounded-lg border bg-white p-6 shadow-sm", children: [_jsx("h2", { className: "mb-6 text-xl font-semibold text-techtoniq-earth-dark", children: "Regional Earthquakes" }), _jsx("div", { className: "flex items-center justify-center", children: _jsxs("div", { className: "flex flex-col items-center", children: [_jsx(MapPin, { className: "mb-4 h-20 w-20 text-techtoniq-blue opacity-60" }), _jsx("p", { className: "text-center text-techtoniq-earth", children: "Regional earthquake data would be displayed here" })] }) })] }), _jsxs("div", { className: "rounded-lg border bg-white p-6 shadow-sm", children: [_jsx("h2", { className: "mb-6 text-xl font-semibold text-techtoniq-earth-dark", children: "Regional Map" }), _jsx("div", { className: "flex items-center justify-center", children: _jsxs("div", { className: "flex flex-col items-center", children: [_jsx(Map, { className: "mb-4 h-20 w-20 text-techtoniq-blue opacity-60" }), _jsx("p", { className: "text-center text-techtoniq-earth", children: "Regional earthquake map would be displayed here" })] }) })] })] }) })] }));
};
export default EarthquakeByRegion;
